language: elixir

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.3
    - otp_release: 19.1
      elixir: 1.3.3

sudo: false

script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test mix credo
  - mix test

notifications:
  email: false
